name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      user: actions/checkout@v2

    - name: Create node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '10.2.3'

    - name: install packages
      run: npm install

    - name: build
      run: npm run build

    - name: Run unit tests
      run: npm run test:unit